### ISSUE TITLE
有个问题，可视模式选择文字，切换到normal模式，文字的选择高亮还在

### ISSUE THREAD

**Issue by StephenWu5** [rcmdnk/vim_ahk#35]
有个问题，可视模式选择文字，切换到normal模式，文字的选择高亮还在？可以去掉该文字选择高亮效果吗

**Comment by rcmdnk** [comment]
Could you please give me more information?
- vim_emu version
- Windows version
- Application on which you have a problem (only on a specific application, or on any?)

**Comment by StephenWu5** [comment]
vim version 0.4.2
win10,
any application

my proplem is that when it change to V mode, I select these words.and it change to normal
mode, these words still have been selected!! I don't want these words have been selected and I want they are free.  my english is not good , I hope you know my word.

![11](https://user-images.githubusercontent.com/32475322/62288009-009aa000-b48e-11e9-8a45-2752ed93c4a1.gif)

**Comment by rcmdnk** [comment]
Thanks for the clarification.
You are right.

I updated to cancel the selection when entering to Normal mode.
Actually, there was the same problem after Copy and I just implemented Right-Left cursor move on there.
But I updated this behavior, too.

As of Windows' function, there is no direct cancel method (such Esc can not work to cancel the selection).
Therefore, I implemented to move the cursor Left and Right for NotePad and Explorer.
On the other hand, for other applications, I implemented only Right move.

This is because of that cursor behaviors after selection are different on them.


On NotePad or Explorer, the cursor remains the same place after the selection.
In this case, to cancel the selection, cursor move of right-left set the cursor in the same place.
(it will be different place only when the cursor is at the end of the document, though...)

On other applications such Word or WordPad, if you push right or left cursor after selection,
the cursor moves to the right or left side of the selection, respectively.
So, I just implemented "right" for these applications, as it is difficult to know the current cursor position in AHK.


As a result, behaviors are a bit different on these applications.
But anyways, the selection is canceled when you enter the Normal mode.

**Comment by StephenWu5** [comment]
thank you and I see. your English is well，where are you come from?

**Comment by rcmdnk** [comment]
I'm Japanese.
Anyway, you can write in Chinese as current Google Translate is very powerful and I could easily understand the first your comment :grin:

**Comment by StephenWu5** [comment]
😄😄
