### ISSUE TITLE
Let's talk refactoring

### ISSUE THREAD

**Issue by BlueDrink9** [rcmdnk/vim_ahk#39]
I just came back to this codebase, and golly it's hard to navigate. It's like doing it fresh all over again, and it reminded me how much we need things like #34.

However, this code needs more than just splitting into files.

The settings UI should be refactored so that each component's data is kept together, and adding new settings should be as simple as calling a single function with the relevant data,
similar to what I did with checkboxes.

Also, why on earth does _every *single* **variable**_ start with the word "vim"? This seems seriously unneccessary, especially since the script is titled "vim.ahk". It makes
reading and writing the code harder, and I would like permission to change it.

A lot of the code is a repetition of every mapped key, in a slightly different context. If possible, I want to look into making that a single file to `#include`, changing some macro
where needed.

Let me know your thoughts. AHK can be brittle to work with, but I think this project should still have enough life left to make taking care of the code worthwhile.

(I hope I'm not coming across too aggressively)

**Comment by rcmdnk** [comment]
Thanks for the suggestions.
Sorry, I could not spend enough time on this, but I will work on this for the next few days.

> The settings UI

It could be better. The code is just a pileup of histories for now...

> every single variable starts with the word "vim"? 

This is because I would like to remain an option to use this script in the other script, which I'm doing.
`VIM` prefix for variables, functions can avoid conflict from the parent script (or another script which is used at the same time).

> Splitting file

Now it is almost 2000 lines and one file maintenance is not a good idea, I agree.
And there is an executable if the user wants to use it standalone,
then I'm not against to split the file.

**Comment by BlueDrink9** [comment]
> use this script in the other script,

Ah, thanks for that explanation. Could we consider putting it into a class? Or even `#include`ing inside a class declaration in other scripts?

I'm happy to help with the refactoring, I just want to know what limits or design decisions you want to go with. If you want to be the driver, feel free to just assign me limited tasks to do

**Comment by rcmdnk** [comment]
> putting it into a class? 

It should be better.
Maybe better to start to use a class and make files if needed (maybe better to make a top file for standalone and included script..?)

**Comment by BlueDrink9** [comment]
Shall I draft a PR and we can collaborate on it?

**Comment by rcmdnk** [comment]
Yes, please, thanks!
