### ISSUE TITLE
Long press <C-[> to return to normal mode, allowing single press to send esc to window

### ISSUE THREAD

**Issue by LeonT-A** [rcmdnk/vim_ahk#58]
Hello, I just found this script today and I'm loving it. However, I ran into an issue right away.

For those of us who use `<C-[>` instead of `<Esc>`, there is no way for us to send esc to the window.

In the settings for vim_ahk, only long-press `<Esc>` will return you to normal mode. 

In Vim, `<C-[>` is equivalent to `<Esc>`, so it should do the same things.

`:h <Esc>`
```
notation	      meaning	     equivalent	decimal         value(s)	
-----------------------------------------------------------------------
<Esc>	          escape		   CTRL-[	   27	         *escape* *<Esc>*
```

P.S
In the latest vim_ahk.exe (0.8), icons are not working (Windows 10).

**Comment by LeonT-A** [comment]
On a related not, when you're in normal mode, `<C-[>` does not send esc to the window. It currently does nothing.

**Comment by rcmdnk** [comment]
Thanks for the report.
Although `VimLongEscNormal` option was implemented for `Esc`,
there was a difficulty for `Ctrl`-`[` because it is the conbination of the keys.

But it seems it works if only `[` is checked for the waitkey.
I will check a little bit more and implement a kine of `VimLongCtrlBracketNormal` option/function.

> In the latest vim_ahk.exe (0.8), icons are not working (Windows 10).
About the ICONS, you are right and maybe it has been there since when the icon was implemented.
It works if you launch from the script, but it seems it does not work if it is launched by compiled vim_ahk.exe.

Please let me check.

> On a related not, when you're in normal mode, <C-[> does not send esc to the window. It currently does nothing.

This is intended to work so,
because I would like to avoid a malfunction by pushing `ESC` several times to change to normal mode.

But it may be good to have an option to send `ESC` or `C-[` directly in the normal mode.

I'll look into it, too.

**Comment by rcmdnk** [comment]
At v0.8.1,
`VimLongEscNormal` is enabled for `Ctrl`-`[`, too.

If you press `Ctrl`-`[` for more than 0.5sec, then original `Ctrl`-`[` will be sent.

If you `VimLongEscNormal := 1` or check `Long press esc to enter normal mode` in the setting menu,
short press will send `Ctrl`-`[` and long press will change to the normal mode.

It may be better to separate options for `ESC` and `Ctrl`-`[`.
Will update later.

**Comment by rcmdnk** [comment]
ok, at v0.8.3:

There are 4 new options:

- ESC to enter Normal mode
	- Long press ESC to enter Normal mode
- Ctrl[ to enter Normal mode
	- Long press Ctrl-[ to enter Normal mode

You can choose if these keys are enabled or not separately,
and can choose to assign single press or long press, too.

So that 

> Long press <C-[> to return to normal mode, allowing single press to send esc to window

this should be OK.

> In the latest vim_ahk.exe (0.8), icons are not working (Windows 10).

About this, exe file does not include incons.
Therefore, I created new zip file, which has *vim_ahk** directory like:

```
vim_ahk
   |-- vim_ahk.exe
   |-- vim_ahk_icons
   |    |-- command.ico
   |    |-- disabled.ico
   |    |-- insert.ico
   |    |-- normal.ico
   |    |-- visual.ico
```

Please place this folder where you like, and launch **vim_ahk.exe**.
It should be in the same folder with **vim_ahk_icons** folder.
Then icons are also enabled for executable.

> It may be better to separate options for ESC and Ctrl-[.

remaining homework...

**Comment by rcmdnk** [comment]
At v0.8.5, you can choose to send ESC by Ctrl-[ in the normal mode by choosing following options:

* Ctrl-[ to ESC
* Ctrl-[ to enter the normal mode
    * Send Ctrl-[ by Ctrl-[ at the normal mode

Could you please try v0.8.5.

I think all of your pains have been relieved.
