### ISSUE TITLE
Paste of an incomplete line doesn't work

### ISSUE THREAD

**Issue by nadya-p** [rcmdnk/vim_ahk#7]
Yank few characters, then paste it using p or P.

This works ok for the entire lines.

**Comment by rcmdnk** [comment]
Thank you for the feedback.
I'm in my travel and don't have windows on my hand,
will check in the next (or the next after next) week.

**Comment by rcmdnk** [comment]
As long as I tested, it works fine even for a few characters.
On which application are you using?

Does "doesn't work" mean you can not paste anything, or paste wrong character (such previously yanked one)?

I've updated vim_ahk to remove selection shade after yank,
so you can see visually `y` works or not.

You can test `p` by copying some words by `C-c` as normally and just do `p` in normal mode,
or you can test `y` by copying by `y` and pasting by `C-v`,
because `y` and `p` are using Windows' clipboard.

If you can identify where is wrong, then I might be able to investigate more.
